#!/usr/bin/env bash
# Deploy counter and vault contracts to Stellar testnet.
# Usage: ./scripts/deploy.sh
set -euo pipefail

NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
# Native XLM SAC address on testnet
NATIVE_TOKEN="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"

echo "=== Stellar Test dApp Deployer ==="

# Generate or reuse deployer identity
if ! stellar keys address deployer &>/dev/null; then
  echo "Generating deployer keypair..."
  stellar keys generate deployer --network "$NETWORK"
  echo "Funding deployer via friendbot..."
  curl -s "https://friendbot.stellar.org/?addr=$(stellar keys address deployer)" > /dev/null
  echo "Deployer funded: $(stellar keys address deployer)"
else
  echo "Using existing deployer: $(stellar keys address deployer)"
fi

DEPLOYER_ADDRESS=$(stellar keys address deployer)

# Build contracts
echo "Building contracts..."
stellar contract build

# Deploy counter (no constructor args)
echo "Deploying counter contract..."
COUNTER_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/counter.wasm \
  --source deployer \
  --network "$NETWORK" 2>&1 | tail -1)
echo "Counter deployed: $COUNTER_ID"

# Deploy vault (with constructor: admin + native token)
echo "Deploying vault contract..."
VAULT_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/vault.wasm \
  --source deployer \
  --network "$NETWORK" \
  -- \
  --admin "$DEPLOYER_ADDRESS" \
  --token "$NATIVE_TOKEN" 2>&1 | tail -1)
echo "Vault deployed: $VAULT_ID"

# Write contract IDs to .env.contracts for the frontend to use
cat > .env.contracts <<EOF
# Auto-generated by deploy.sh — do not edit manually
PUBLIC_COUNTER_CONTRACT_ID="$COUNTER_ID"
PUBLIC_VAULT_CONTRACT_ID="$VAULT_ID"
PUBLIC_DEPLOYER_ADDRESS="$DEPLOYER_ADDRESS"
EOF

echo ""
echo "=== Deployment Complete ==="
echo "Counter:  $COUNTER_ID"
echo "Vault:    $VAULT_ID"
echo "Deployer: $DEPLOYER_ADDRESS"
echo ""
echo "Contract IDs written to .env.contracts"
